---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
  templates:
  - event
- type: document
  path: _data/team.yml
  label: Team
- type: directory
  path: _articles
  label: In Focus
  create: all
  match: "**/*"
  templates:
  - in-focus
- type: directory
  path: _content
  label: Content
  create: all
  match: "**/*"
  templates:
  - page
upload_dir: static
public_path: "/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: 'bundle config set --local path ''vendor/bundle''
    && bundle install  '
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
